# Generated by Django 5.2.11 on 2026-03-01 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_employee_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('electricity', 'Electricity'), ('rent', 'Rent'), ('water', 'Water'), ('internet', 'Internet'), ('maintenance', 'Maintenance'), ('supplies', 'Supplies'), ('other', 'Other')], db_index=True, max_length=30)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='employees.employee')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]

