# Generated by Django 4.2.27 on 2026-02-25 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('father_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('work_days', models.TextField(default='[]')),
                ('join_date', models.DateField()),
                ('membership_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('intern', 'Intern')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'indexes': [models.Index(fields=['status'], name='employees_status_0192ac_idx'), models.Index(fields=['membership_type'], name='employees_members_5b2bab_idx'), models.Index(fields=['join_date'], name='employees_join_da_8f8d98_idx')],
            },
        ),
    ]
