# Generated by Django 4.2.27 on 2026-02-26 06:55

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_seed_employee_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.employee_picture_upload_path),
        ),
    ]
