# Generated by Django 5.2.11 on 2026-02-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remap_legacy_library_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('users', 'Users'), ('books', 'Books'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('customers', 'Customers'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=50),
        ),
    ]
