# Generated by Django 5.2.11 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_permission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(
                choices=[
                    ('users', 'Users'),
                    ('books', 'Books'),
                    ('sales', 'Sales'),
                    ('purchases', 'Purchases'),
                    ('customers', 'Customers'),
                    ('employees', 'Employees'),
                    ('lending', 'Lending'),
                    ('reports', 'Reports'),
                    ('settings', 'Settings'),
                ],
                max_length=50,
            ),
        ),
    ]

