# Generated by Django 5.2.11 on 2026-03-01 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_seed_books_permissions'),
        ('customers', '0002_seed_customers_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(db_index=True)),
                ('rent_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('returned', 'Returned'), ('not_returned', 'Not Returned')], db_index=True, default='not_returned', max_length=20)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], db_index=True, default='unpaid', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank Transfer'), ('online', 'Online'), ('other', 'Other')], db_index=True, default='cash', max_length=20)),
                ('returned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lendings', to='books.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lendings', to='customers.customer')),
            ],
            options={
                'db_table': 'lendings',
            },
        ),
    ]

